
theme: jekyll-theme-minimal
title: Aitor Arrieta
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: Lecturer and Researcher at Mondragon University
twitter:
    - username: aitorarrieta
social:
  links:
    - https://twitter.com/aitorarrieta
description: Aitor Arrieta is a Professor at Mondragon University. His main researh interests are Cyber-Physical Systems testing, regression testing, search-based software testing and simulation-based testing.

bio: Aitor Arrieta is a lecturer and researcher at Mondragon University. He got his PhD in software engineering at Mondragon University in 2017. His research interests lie in the field of software testing (e.g., search-based software testing, test oracle problem, regression testing, debugging and repair), especially on testing untestable systems, such as Cyber-Physical Systems, highly configurable systems and Machine-Learning based systems. <p>


    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:aarrieta@mondragon.edu">aarrieta@mondragon.edu</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://www.twitter.com/aitorarrieta">@aitorarrieta</a>

logo: assets/AitorArrieta.jpg
logo_title: Aitor Arrieta
